//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestGest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagamentoSet
    {
        public int Id { get; set; }
        public float Valor { get; set; }
        public int IdMetodoPagamento { get; set; }
        public int IdPedido { get; set; }
        public Nullable<int> PedidoSetId { get; set; }
    
        public virtual MetodoPagamentoSet MetodoPagamentoSet { get; set; }
        public virtual PedidoSet PedidoSet { get; set; }

        public override string ToString(){
            return this.MetodoPagamentoSet.ToString() +" : "+this.Valor+"€";
        }
    }
}
