//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestGest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoSet()
        {
            this.PagamentoSet = new HashSet<PagamentoSet>();
            this.ItemMenuSet = new HashSet<ItemMenuSet>();
        }
    
        public int Id { get; set; }
        public decimal ValorTotal { get; set; }
        public int IdEstado { get; set; }
        public int IdRestaurante { get; set; }
        public int IdCliente { get; set; }
        public int IdTrabalhador { get; set; }
    
        public virtual EstadoSet EstadoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoSet> PagamentoSet { get; set; }
        public virtual PessoaSet_Cliente PessoaSet_Cliente { get; set; }
        public virtual RestauranteSet RestauranteSet { get; set; }
        public virtual PessoaSet_Trabalhador PessoaSet_Trabalhador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMenuSet> ItemMenuSet { get; set; }

        public override string ToString(){
            return "[#"+this.Id+"] "+this.ValorTotal+"€"+this.RestauranteSet.ToString();
        }
    }
}
