//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestGest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaSet_Trabalhador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PessoaSet_Trabalhador()
        {
            this.PedidoSet = new HashSet<PedidoSet>();
        }
    
        public int Salario { get; set; }
        public string Posicao { get; set; }
        public int IdRestaurante { get; set; }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoSet> PedidoSet { get; set; }
        public virtual PessoaSet PessoaSet { get; set; }
        public virtual RestauranteSet RestauranteSet { get; set; }
        
        public override string ToString(){
            return this.PessoaSet.ToString() + ", " + this.Posicao;
        }
        
    }
}
