//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestGest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaSet
    {
        public PessoaSet()
        {
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public int Telemovel { get; set; }
        public int Morada_Id { get; set; }
    
        public virtual MoradaSet MoradaSet { get; set; }
        public virtual PessoaSet_Cliente PessoaSet_Cliente { get; set; }
        public virtual PessoaSet_Trabalhador PessoaSet_Trabalhador { get; set; }
    }
}
